#if [ -z "$1" ]; then
#echo Input Password is missing
#exit 1
#fi
#source common.sh
#component=shipping
#MAVEN
#
#dnf install mysql -y
#for file in schema app-user master-data; do
#mysql -h mysql-dev.sdevops09.online -uroot -p$1 < /app/db/$file.sql
#
#done


- name: Load Maven
  ansible.builtin.import_role:
    name: common
    tasks_from: maven

- name: Install Mysql Client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load schema
  ansible.builtin.shell: mysql -h mysql-dev.sdevops09.online -uroot -p$1 < /app/db/schema.sql

- name: Load schema
  ansible.builtin.shell: mysql -h mysql-dev.sdevops09.online -uroot -p$1 < /app/db/app-user.sql

- name: Load schema
  ansible.builtin.shell: mysql -h mysql-dev.sdevops09.online -uroot -p$1 < /app/db/master-data.sql