- name: copy component service file
  ansible.builtin.copy:
    src: "{{ component }}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: start service
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    state: restarted
    name: "{{ component }}"